2021-10-24 12:04:33,296 INFO    MainThread:20756 [wandb_setup.py:_flush():69] setting env: {}
2021-10-24 12:04:33,296 INFO    MainThread:20756 [wandb_setup.py:_flush():69] setting login settings: {'anonymous': 'must'}
2021-10-24 12:04:33,297 INFO    MainThread:20756 [wandb_init.py:_log_setup():342] Logging user logs to D:\project\gitExchange\wall-unet\wandb\run-20211024_120433-1lnu7bmz\logs\debug.log
2021-10-24 12:04:33,297 INFO    MainThread:20756 [wandb_init.py:_log_setup():343] Logging internal logs to D:\project\gitExchange\wall-unet\wandb\run-20211024_120433-1lnu7bmz\logs\debug-internal.log
2021-10-24 12:04:33,297 INFO    MainThread:20756 [wandb_init.py:init():375] calling init triggers
2021-10-24 12:04:33,297 INFO    MainThread:20756 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-10-24 12:04:33,297 INFO    MainThread:20756 [wandb_init.py:init():424] starting backend
2021-10-24 12:04:33,297 INFO    MainThread:20756 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=spawn, using: spawn
2021-10-24 12:04:33,301 INFO    MainThread:20756 [backend.py:ensure_launched():135] starting backend process...
2021-10-24 12:04:33,356 INFO    MainThread:20756 [backend.py:ensure_launched():140] started backend process with pid: 9340
2021-10-24 12:04:33,357 INFO    MainThread:20756 [wandb_init.py:init():429] backend started and connected
2021-10-24 12:04:33,358 INFO    MainThread:20756 [wandb_init.py:init():477] updated telemetry
2021-10-24 12:04:33,359 INFO    MainThread:20756 [wandb_init.py:init():500] communicating current version
2021-10-24 12:04:34,154 INFO    MainThread:20756 [wandb_init.py:init():505] got version response 
2021-10-24 12:04:34,154 INFO    MainThread:20756 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-10-24 12:05:04,169 INFO    MainThread:20756 [interface.py:_communicate_run():651] couldn't get run from backend
2021-10-24 12:05:04,169 ERROR   MainThread:20756 [wandb_init.py:init():518] backend process timed out
2021-10-24 12:05:04,169 ERROR   MainThread:20756 [wandb_init.py:init():527] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-10-24 12:05:04,179 ERROR   MainThread:20756 [wandb_init.py:init():801] error
Traceback (most recent call last):
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\wandb_init.py", line 775, in init
    run = wi.init()
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\wandb_init.py", line 531, in init
    backend.cleanup()
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\backend\backend.py", line 167, in cleanup
    self.interface.join()
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\interface\interface.py", line 830, in join
    _ = self._communicate(record)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\interface\interface.py", line 539, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\interface\interface.py", line 544, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
