2021-10-24 12:04:33,942 INFO    MainThread:9340 [internal.py:wandb_internal():89] W&B internal server running at pid: 9340, started at: 2021-10-24 12:04:33.933054
2021-10-24 12:04:33,944 DEBUG   HandlerThread:9340 [handler.py:handle_request():126] handle_request: check_version
2021-10-24 12:04:33,945 INFO    WriterThread:9340 [datastore.py:open_for_write():77] open: D:\project\gitExchange\wall-unet\wandb\run-20211024_120433-1lnu7bmz\run-1lnu7bmz.wandb
2021-10-24 12:04:33,947 DEBUG   SenderThread:9340 [sender.py:send():182] send: header
2021-10-24 12:04:33,947 DEBUG   SenderThread:9340 [sender.py:send_request():196] send_request: check_version
2021-10-24 12:04:34,155 DEBUG   SenderThread:9340 [sender.py:send():182] send: run
2021-10-24 12:04:34,157 INFO    SenderThread:9340 [sender.py:_maybe_setup_resume():422] checking resume status for None/U-Net/1lnu7bmz
2021-10-24 12:04:35,167 INFO    WriterThread:9340 [datastore.py:close():281] close: D:\project\gitExchange\wall-unet\wandb\run-20211024_120433-1lnu7bmz\run-1lnu7bmz.wandb
2021-10-24 12:04:35,167 INFO    HandlerThread:9340 [handler.py:finish():683] shutting down handler
2021-10-24 12:04:35,167 ERROR   MainThread:9340 [internal.py:wandb_internal():157] Thread SenderThread:
Traceback (most recent call last):
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\apis\normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\internal\internal_api.py", line 694, in run_resume_status
    variable_values={"entity": entity, "project": project_name, "name": name,},
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\internal\internal_api.py", line 130, in execute
    return self.client.execute(*args, **kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\vendor\gql-0.2.0\gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "E:\conda\install\envs\unet\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "E:\conda\install\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "E:\conda\install\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "E:\conda\install\envs\unet\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "E:\conda\install\envs\unet\lib\site-packages\urllib3\connection.py", line 506, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "E:\conda\install\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "E:\conda\install\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "E:\conda\install\envs\unet\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "E:\conda\install\envs\unet\lib\ssl.py", line 773, in __init__
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\internal\internal_util.py", line 52, in run
    self._run()
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\internal\internal_util.py", line 102, in _run
    self._process(record)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\internal\internal.py", line 290, in _process
    self._sm.send(record)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\internal\sender.py", line 184, in send
    send_handler(record)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\internal\sender.py", line 593, in send_run
    error = self._maybe_setup_resume(run)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\internal\sender.py", line 425, in _maybe_setup_resume
    entity=entity, project_name=run.project, name=run.run_id
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\apis\normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "E:\conda\install\envs\unet\lib\site-packages\six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\apis\normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\internal\internal_api.py", line 694, in run_resume_status
    variable_values={"entity": entity, "project": project_name, "name": name,},
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\sdk\internal\internal_api.py", line 130, in execute
    return self.client.execute(*args, **kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\wandb\vendor\gql-0.2.0\gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "E:\conda\install\envs\unet\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "E:\conda\install\envs\unet\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "E:\conda\install\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "E:\conda\install\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "E:\conda\install\envs\unet\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "E:\conda\install\envs\unet\lib\site-packages\urllib3\connection.py", line 506, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "E:\conda\install\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "E:\conda\install\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "E:\conda\install\envs\unet\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "E:\conda\install\envs\unet\lib\ssl.py", line 773, in __init__
    raise ValueError("check_hostname requires server_hostname")
wandb.errors.CommError: check_hostname requires server_hostname
2021-10-24 12:04:37,236 INFO    MainThread:9340 [internal.py:handle_exit():76] Internal process exited
